"""Gate 2h's heterogeneous path: the per-creature design writer, and a
per-slot policy over a mixed team.

    MUJOCO_GL=osmesa PYTHONPATH=. .venv/bin/python \
        -m rower_soccer.competevo_port.gate_hetero [--steps 20]

`tests/test_design_parity.py` establishes the ANT's writer to machine epsilon
against CompetEvo's own emitted MJCF. There is no equivalent cross-stack
reference for the bug or the spider -- their driver only ever ran the ant --
so this file builds the reference the other way round: it bakes the genome into
the GEOMETRY of the scene XML and lets MuJoCo's compiler derive everything
else. That is exactly the split the writer has to get right, because the writer
computes in closed form what the compiler derives:

    written by the gate's reference XML   fromto, capsule radius, body pos, gear
    DERIVED by the compiler               body_mass, body_inertia, body_ipos,
                                          body_subtreemass, geom_pos,
                                          geom_rbound, geom_aabb, bvh_aabb,
                                          and (via mj_setConst) the three
                                          *_invweight0 / actuator_acc0 fields

so a writer whose per-creature capsule table, per-creature 0.3-vs-0.5 scale, or
inertia formula is wrong for the bug or the spider cannot agree with it.

The geometric half of the reference is not invented here either. Read against
`competevo/evo_envs/agents/dev_bug.py` and `dev_spider.py` (2026-08-26):
`set_design_params` computes `a = 1 + SCALE_MAX * s`, `b = 1 + 0.5 * SCALE_MAX
* s` and then, per leg L, multiplies body `L+1`'s geom `fromto` by `a[5L]`,
body `1(L+1)`'s `pos` by `a[5L]`, its geom `size` by `a[5L+1]` and `fromto` by
`a[5L+2]`, body `11(L+1)`'s `pos` by `a[5L+2]`, its `size` by `a[5L+3]` and
`fromto` by `a[5L+4]`, and the two motors' gears by `b[5L+1]` and `b[5L+3]`.
`SCALE_MAX` is 0.3 / 0.5 / 1.2 (the spider's is the one `creatures.py`
deliberately lowers to 0.5). `scaled_body_xml` / `scaled_motor_xml` below are
that, and nothing else -- which is why they read `spec.genome_table()` rather
than reimplement it, and why an error IN that table would be invisible to this
gate and has to be caught by reading their source, as above.

The reference scene is generated by `team_scene.dev_team_xml` ITSELF, with
`creatures.body_xml` / `motor_xml` temporarily swapped for scaled versions.
That is deliberate: body, geom and actuator ids, the contact bitmask, the
spawn poses and the goal assignment then come from the production code path, so
the two models differ in geometry and in nothing else, and the comparison is
index-for-index.

The checks
----------
  1. **Per creature, alone.** ant / bug / spider in a homogeneous 4-agent
     scene, random genomes, every written field against a fresh compile. Same
     1e-12 bar as `test_design_parity`, extended to `bvh_aabb` and the
     `mj_setConst` block.
  2. **Mixed scene, per-agent isolation.** Writing agent i's genome moves
     agent i's geoms, bodies and gears and NOTHING else. This is the check
     that catches the `_gather` padding trap: `_gather` returns 1.0 at a `-1`
     parameter index, so a padded row does not write nothing -- it writes the
     BASE capsule to whatever `geom_id` it names.
  3. **Negative control.** The same scene with `design.py`'s `*_keep` tensors
     disabled, which is precisely "pad the ragged tables the way `dev_env`
     pads its observation and hope". It must FAIL, and it must fail by
     corrupting a geom nobody's genome owns.
  4. **A max-scale ant beside a spider** reproduces a fresh compile of that ant
     genome, capsule by capsule -- the concrete case in which a padded write
     from the spider-width table would silently restore base geometry on the
     ant.
  5. **Compositions run.** Several mixed 4-agent scenes build, reset and step
     with finite observations, and a per-slot policy acts on them, is trained
     through the flat (minibatch) dispatch, and closes a `CoEvoPPO` iteration.
"""

import argparse
import contextlib
import dataclasses
import sys
import xml.etree.ElementTree as ET

import mujoco
import numpy as np
import torch

from rower_soccer.competevo_port import team_scene
from rower_soccer.competevo_port.creatures import CREATURES
from rower_soccer.competevo_port.design import (CONST_FIELDS,
                                                CPU_EXTRA_FIELDS,
                                                WRITTEN_FIELDS, HostConstants,
                                                build_design_spec,
                                                design_fields)
from rower_soccer.competevo_port.team_scene import build_dev_team_scene

TOL = 1e-12
RESULTS = []


def check(name, ok, detail=""):
    RESULTS.append(bool(ok))
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}" + (f"  -- {detail}" if detail else ""))
    return bool(ok)


# ---------------------------------------------------------------------------
# the reference: the same scene, with the genome baked into the geometry
# ---------------------------------------------------------------------------
def _g(*v):
    """Full-precision MJCF numbers. `creatures._fmt` uses `%g`, which is right
    for hand-written constants and would put a 1e-7 floor under a 1e-12
    comparison."""
    return " ".join(f"{float(x):.17g}" for x in v)


def scaled_body_xml(spec, agent_id, pos, euler, s):
    """`creatures.body_xml` with `s` applied to the GEOMETRY only.

    Per the genome table, for each scaled body: its capsule's `fromto` by the
    length factor, its capsule's radius by the radius factor (where it has
    one), and its own `pos` by the parent link's length factor. Scaling the
    whole `fromto` is what scales both the capsule's half-length and its
    midpoint, which is the writer's `h *= f_len`, `geom_pos *= f_len`.

    Everything the compiler derives from that is left to the compiler.
    """
    a = 1.0 + spec.geom_scale * np.asarray(s, dtype=np.float64)
    tbl = {row[0]: row[1:] for row in spec.genome_table()}
    p = f"agent{agent_id}"
    root = spec.tree().getroot()
    body = root.find("body")

    def nums(el, attr):
        return [float(x) for x in el.get(attr).split()]

    def walk(el, parent_local):
        local = el.get("name") or parent_local
        if el.tag == "body" and el.get("name") in tbl:
            _, _, pos_param, _ = tbl[el.get("name")]
            if pos_param is not None:
                el.set("pos", _g(*[v * a[pos_param] for v in nums(el, "pos")]))
        if el.tag == "geom" and parent_local in tbl:
            l_param, r_param, _, _ = tbl[parent_local]
            assert el.get("fromto") is not None, (
                f"{spec.key}: scaled geom of body {parent_local} has no fromto")
            el.set("fromto", _g(*[v * a[l_param] for v in nums(el, "fromto")]))
            if r_param is not None:
                el.set("size", _g(nums(el, "size")[0] * a[r_param]))
        if el.tag in ("body", "joint") and el.get("name") is not None:
            el.set("name", f"{p}/{el.get('name')}")
        if el.tag == "geom":
            el.set("name", f"{p}/geom_{parent_local}")
            el.set("class", p)
        for child in list(el):
            walk(child, local)

    walk(body, "0")
    body.set("pos", _g(*pos))
    body.set("euler", _g(*euler))
    ET.indent(body, space="  ")
    return ET.tostring(body, encoding="unicode")


def scaled_motor_xml(spec, agent_id, s):
    """`creatures.motor_xml` with the gear factors applied."""
    b = 1.0 + spec.gear_scale * np.asarray(s, dtype=np.float64)
    gear_of = {row[0]: row[4] for row in spec.genome_table()}
    p = f"agent{agent_id}"
    out = []
    for joint, gear in zip(spec.motor_joints(), spec.motor_gears()):
        local = joint[:-len("_joint")]
        k = gear_of[local]
        g = gear if k is None else gear * b[k]
        out.append(f'    <motor ctrllimited="true" ctrlrange="-1.0 1.0"'
                   f' joint="{p}/{joint}" gear="{_g(g)}"'
                   f' name="{p}/{joint}" class="{p}"/>')
    return "\n".join(out)


@contextlib.contextmanager
def _scaled_emitters(scale):
    """`team_scene.dev_team_xml` emitting the designed geometry.

    `dev_team_xml` imports `body_xml`/`motor_xml` from `creatures` at CALL
    time, so swapping the module attributes is enough -- and it means the
    reference model is produced by the production scene builder, with the same
    ids, bitmask and poses as the model the writer writes into.
    """
    from rower_soccer.competevo_port import creatures as C
    ob, om = C.body_xml, C.motor_xml
    C.body_xml = lambda sp, i, pos, eul: scaled_body_xml(sp, i, pos, eul,
                                                         scale[i])
    C.motor_xml = lambda sp, i: scaled_motor_xml(sp, i, scale[i])
    try:
        yield
    finally:
        C.body_xml, C.motor_xml = ob, om


def reference_model(names, scale):
    """A FRESH COMPILE of the scene `names` at genome `scale` `[A, design_dim]`."""
    with _scaled_emitters(scale):
        return mujoco.MjModel.from_xml_string(
            team_scene.dev_team_xml(len(names), creatures=names))


def _field(model, name):
    a = np.asarray(getattr(model, name), dtype=np.float64)
    return a.reshape(model.ngeom, 2, 3) if name == "geom_aabb" else a


def random_genome(names, rng):
    """`[A, max_design_dim]`, each agent's own width filled and the padding 0 --
    which is what `dev_env.reset_idx` produces."""
    specs = [CREATURES[n] for n in names]
    W = max(sp.design_dim for sp in specs)
    S = np.zeros((len(names), W))
    for i, sp in enumerate(specs):
        S[i, :sp.design_dim] = rng.uniform(-1.0, 1.0, sp.design_dim)
    return S


def writer_vs_compile(names, S, label):
    """Max |writer - fresh compile| over every field the writer owns."""
    model, meta = build_dev_team_scene(len(names), creatures=names)
    spec = build_design_spec(model, meta)
    fields = design_fields(spec, torch.as_tensor(S[None]))
    ref = reference_model(names, S)
    rep = {}
    for f in WRITTEN_FIELDS + CPU_EXTRA_FIELDS:
        t = _field(ref, f)
        ours = fields[f][0].numpy().reshape(t.shape)
        rep[f] = float(np.abs(ours - t).max())
    consts = HostConstants(model, spec).compute(torch.as_tensor(S[None]))
    for f in CONST_FIELDS:
        t = _field(ref, f)
        sc = max(float(np.abs(t).max()), 1e-12)
        rep[f + " (rel)"] = float(
            np.abs(consts[f][0].reshape(t.shape) - t).max() / sc)
    worst = max(rep.values())
    print(f"    {label}: worst {worst:.3e} over {len(rep)} fields "
          f"({max(rep, key=rep.get)})")
    return rep, model, meta, spec, ref


# ---------------------------------------------------------------------------
# ownership: which geoms / bodies / actuators belong to which agent
# ---------------------------------------------------------------------------
def _owner(name):
    return int(name.split("/")[0][5:]) if name.startswith("agent") else -1


def owners(model):
    g = np.array([_owner(model.geom(i).name) for i in range(model.ngeom)])
    b = np.array([_owner(model.body(i).name) for i in range(model.nbody)])
    u = np.array([_owner(model.actuator(i).name) for i in range(model.nu)])
    return g, b, u


# ---------------------------------------------------------------------------
# 1-4. the writer
# ---------------------------------------------------------------------------
def section_writer(seed):
    rng = np.random.default_rng(seed)

    print("\n[1] per creature, alone in a 4-agent scene: writer == fresh compile")
    for key in ("ant", "bug", "spider"):
        names = [key] * 4
        S = random_genome(names, rng)
        rep, *_ = writer_vs_compile(names, S, key)
        check(f"{key}: every design-derived field matches a fresh compile",
              max(rep.values()) < TOL,
              f"worst {max(rep.values()):.2e} < {TOL:.0e}")

    print("\n[2] mixed scene: writing agent i moves ONLY agent i")
    names = ["ant", "spider", "bug", "ant"]
    model, meta = build_dev_team_scene(4, creatures=names)
    spec = build_design_spec(model, meta)
    gown, bown, uown = owners(model)
    W = spec.design_dim
    base = design_fields(spec, torch.zeros(1, 4, W, dtype=torch.float64))
    leaks = []
    for i in range(4):
        S = np.zeros((1, 4, W))
        S[0, i, :meta.design_dims[i]] = rng.uniform(0.5, 1.0,
                                                    meta.design_dims[i])
        f = design_fields(spec, torch.as_tensor(S))
        moved = {}
        for name in WRITTEN_FIELDS + CPU_EXTRA_FIELDS:
            d = (f[name][0] - base[name][0]).abs()
            d = d.reshape(d.shape[0], -1).max(-1).values.numpy()
            if name.startswith("geom") or name == "bvh_aabb":
                own = gown if name.startswith("geom") else None
            elif name.startswith("body"):
                own = bown
            else:
                own = uown
            moved[name] = d
            if own is None:
                continue        # bvh_aabb is indexed by BVH node, not by geom
            wrong = np.where((d > 0) & (own != i))[0]
            # `body_subtreemass` legitimately moves on the WORLD body (0): it
            # is the sum over the whole tree, so any agent changing mass
            # changes it. Nothing else may move.
            if name == "body_subtreemass":
                wrong = wrong[own[wrong] != -1]
            if wrong.size:
                leaks.append((i, name, wrong[:4].tolist()))
        own_moved = int((moved["geom_size"] > 0).sum())
        check(f"agent {i} ({names[i]}): its own {own_moved} capsules move",
              own_moved == 3 * CREATURES[names[i]].n_legs,
              f"{own_moved} geoms, expected {3 * CREATURES[names[i]].n_legs}")
    check("no write leaks to another agent, the floor or the goal rods",
          not leaks, "" if not leaks else f"{len(leaks)} leaks: {leaks[:3]}")

    print("\n[3] NEGATIVE CONTROL: the same writer with the *_keep guards off")
    # This IS "pad the ragged tables and hope": with the keeps disabled every
    # padded row is written, `_gather` hands it 1.0 (= base geometry), and its
    # padded `geom_id` of 0 names the floor.
    naive = dataclasses.replace(spec, cap_keep=None, body_keep=None,
                                act_keep=None)
    S = np.zeros((1, 4, W))
    S[0, 0, :20] = 1.0                       # the ant, at maximum scale
    good = design_fields(spec, torch.as_tensor(S))
    bad = design_fields(naive, torch.as_tensor(S))
    d_floor = float((bad["geom_size"][0, 0] - good["geom_size"][0, 0]).abs().max())
    d_any = float((bad["geom_size"][0] - good["geom_size"][0]).abs().max())
    check("padding without the keeps DOES corrupt the model", d_any > 1e-6,
          f"max |d geom_size| = {d_any:.3e}")
    check("...and specifically resizes geom 0, which no genome owns",
          d_floor > 1e-6 and gown[0] == -1,
          f"geom 0 ({model.geom(0).name}) moves by {d_floor:.3e}")
    ref = reference_model(names, S[0])
    w_good = float(np.abs(good["geom_size"][0].numpy()
                          - _field(ref, "geom_size")).max())
    w_bad = float(np.abs(bad["geom_size"][0].numpy()
                         - _field(ref, "geom_size")).max())
    check("the guarded writer agrees with the fresh compile and the naive one "
          "does not", w_good < TOL <= w_bad,
          f"guarded {w_good:.2e}, naive {w_bad:.2e}")

    print("\n[4] a MAX-SCALE ant beside a spider is still exactly that ant")
    names = ["ant", "spider", "spider", "ant"]
    S = np.zeros((4, 40))
    S[0, :20] = 1.0                          # ant slot, every part maximal
    S[3, :20] = -1.0                         # the other ant, minimal
    S[1] = rng.uniform(-1, 1, 40)
    S[2] = rng.uniform(-1, 1, 40)
    rep, model, meta, spec, ref = writer_vs_compile(names, S, "ant@+1/spider")
    check("mixed max-scale ant: every field matches a fresh compile",
          max(rep.values()) < TOL, f"worst {max(rep.values()):.2e}")
    # And say out loud that the ant really is at its extreme, so this is not a
    # check that passed because nothing happened.
    gown, _, _ = owners(model)
    a0 = gown == 0
    fields = design_fields(spec, torch.as_tensor(S[None]))
    base = design_fields(spec, torch.zeros(1, 4, 40, dtype=torch.float64))
    ratio = float((fields["geom_size"][0][a0, 1].max()
                   / base["geom_size"][0][a0, 1].max()))
    check("the ant slot really is at the corner of its box (1.3x)",
          abs(ratio - 1.3) < 1e-9, f"longest capsule {ratio:.6f}x base")


# ---------------------------------------------------------------------------
# 5. the env and the per-slot policy
# ---------------------------------------------------------------------------
COMPOSITIONS = (
    ["ant", "ant", "spider", "spider"],      # each side is ant + spider
    ["ant", "spider", "ant", "spider"],      # side 0 all ant, side 1 all spider
    ["bug", "ant", "spider", "bug"],
    ["spider", "bug", "bug", "ant"],
    ["bug"] * 4,                             # homogeneous, but NOT the ant
    ["spider"] * 4,
)


def section_env(steps, seed):
    from rower_soccer.competevo_port.selfplay import CoEvoPPO
    from rower_soccer.competevo_port.slot_policy import (env_is_mixed,
                                                         from_env, wrap_env)
    from rower_soccer.competevo_port.team_env import TeamRunToGoalDevEnv

    print(f"\n[5] mixed scenes run, and a per-slot policy acts on them "
          f"({steps} steps each)")
    for names in COMPOSITIONS:
        torch.manual_seed(seed)
        env = TeamRunToGoalDevEnv(num_worlds=4, use_gpu=False, seed=seed,
                                  scene_kwargs={"creatures": names})
        sides = [[i for i in range(4) if env.meta.team[i] == t] for t in (0, 1)]
        acs = [from_env(env, s) for s in sides]
        wrapped = wrap_env(env, acs[0])
        obs = wrapped.reset()
        finite = bool(torch.isfinite(obs).all())
        assert obs.shape == (4, 4, wrapped.obs_dim), obs.shape
        for _ in range(steps):
            o = obs.float()
            act = torch.zeros(env.n, env.n_agents, env.act_dim,
                              device=env.device, dtype=o.dtype)
            for e, lanes in enumerate(sides):
                act[:, lanes] = acs[e].act(o[:, lanes])[0]
            obs, rew, done, info = wrapped.step(act.to(env.dtype))
            finite = finite and bool(torch.isfinite(obs).all()
                                     and torch.isfinite(rew).all())
        tag = "mixed" if env_is_mixed(env) else "homogeneous"
        check(f"{'/'.join(names)} ({tag}): {steps} steps, finite obs, "
              f"0 diverged",
              finite and env.n_diverged == 0,
              f"obs {env.obs_dim} -> {wrapped.obs_dim}, act {env.act_dim}, "
              f"design {env.design_dims}, motors {env.n_motors}")

    # One composition all the way through the trainer's own loop, because
    # `collect` and `update` take different code paths through the policy (the
    # lane dispatch and the FLAT dispatch) and only the second one reaches
    # `log_prob_flat` / `value_flat`.
    names = ["ant", "bug", "spider", "ant"]
    torch.manual_seed(seed)
    env = TeamRunToGoalDevEnv(num_worlds=4, use_gpu=False, seed=seed,
                              scene_kwargs={"creatures": names})
    sides = [[i for i in range(4) if env.meta.team[i] == t] for t in (0, 1)]
    acs = [from_env(env, s) for s in sides]
    trainer = CoEvoPPO(wrap_env(env, acs[0]), acs=acs, rollout_len=4,
                       blocks=2, epochs=1, minibatch_size=8, device="cpu",
                       seed=seed)
    before = [p.detach().clone() for p in acs[0].parameters()]
    stats = trainer.train_iter()
    moved = sum(1 for p, q in zip(acs[0].parameters(), before)
                if not torch.equal(p.detach(), q))
    check("a CoEvoPPO iteration closes on a mixed composition",
          all(np.isfinite(float(v)) for v in stats.values()),
          ", ".join(f"{k} {float(v):+.4g}" for k, v in list(stats.items())[:4]))
    check("both slots' parameters were actually updated", moved > 0,
          f"{moved}/{len(before)} tensors moved")
    # Each slot must own its own weights: a shared net would be the whole point
    # of Option A missed, and a mixed team cannot express it at all.
    n0 = sum(p.numel() for p in acs[0].nets[0].parameters())
    n1 = sum(p.numel() for p in acs[0].nets[1].parameters())
    check("the two slots are separate nets of different width", n0 != n1,
          f"slot 0 ({names[sides[0][0]]}) {n0:,} params, "
          f"slot 1 ({names[sides[0][1]]}) {n1:,}")

    # The column map is the thing most likely to be silently wrong, so assert
    # it directly rather than inferring it from "the net ran".
    from rower_soccer.competevo_port.slot_policy import (expanded_obs_cols,
                                                         env_own_dims)
    from rower_soccer.competevo_port.team_policy import (ROLE_DIM,
                                                         others_permutation)
    cols = expanded_obs_cols(env)
    own = env_own_dims(env)
    ok = all(c.numel() == 1 + env.design_dims[i] + own[i]
             + 2 * (env.n_agents - 1) + ROLE_DIM
             for i, c in enumerate(cols))
    check("every slot's expanded column map is exactly its policy's width", ok,
          "per agent " + ", ".join(
              f"{names[i]} {int(c.numel())}" for i, c in enumerate(cols)))
    # A probe observation whose entries are their own column indices makes the
    # permutation readable instead of inferred.
    probe = torch.arange(env.obs_dim, dtype=torch.float64).reshape(1, 1, -1)
    probe = probe.expand(1, env.n_agents, env.obs_dim).contiguous()
    wrapped = wrap_env(env, acs[0])
    exp = wrapped._expand(probe)[0]
    base_o = 1 + env.design_dim + env.qpos_idx.shape[1] + env.qvel_idx.shape[1]
    perm = others_permutation(env.n_agents)
    want = torch.tensor([base_o + 2 * o + k for o in perm for k in (0, 1)],
                        dtype=torch.float64)
    check("the expansion permutes the others block to "
          "[opp_near, teammate, opp_far]",
          torch.equal(exp[0, base_o:base_o + want.numel()], want),
          f"perm={perm}")
    check("the expansion is the identity before the others block",
          torch.equal(exp[0, :base_o],
                      torch.arange(base_o, dtype=torch.float64)))
    roles = exp[:, -ROLE_DIM:]
    check("each lane carries ITS OWN role one-hot (front 0,1 / back 2,3)",
          torch.equal(roles, torch.tensor([[1., 0.], [1., 0.],
                                           [0., 1.], [0., 1.]],
                                          dtype=torch.float64)),
          roles.tolist())
    # The gathered slot observation must start with the flag, then that
    # creature's own genome width -- not the padded one. Checked on the ANT
    # slot, whose 20 is strictly narrower than the scene's padded 40; on the
    # spider slot the two coincide and the check would prove nothing.
    l = 0
    d0 = env.design_dims[sides[0][l]]
    assert d0 < env.design_dim, "pick a slot narrower than the padded width"
    g = acs[0]._slot_obs(exp.unsqueeze(0), l)[0]
    check("a slot gathers its OWN genome width, not the padded one",
          float(g[0]) == 0.0 and float(g[d0]) == float(d0)
          and float(g[1 + d0]) == float(1 + env.design_dim),
          f"{names[sides[0][l]]} slot: scale is raw columns 1..{d0}, then the "
          f"sim block resumes at raw column {1 + env.design_dim} (skipping "
          f"{env.design_dim - d0} padded genome columns)")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--steps", type=int, default=20)
    p.add_argument("--seed", type=int, default=0)
    args = p.parse_args()
    torch.manual_seed(args.seed)
    section_writer(args.seed)
    section_env(args.steps, args.seed)
    n_ok = sum(RESULTS)
    print(f"\n{n_ok}/{len(RESULTS)} checks passed")
    return 0 if n_ok == len(RESULTS) else 1


if __name__ == "__main__":
    sys.exit(main())
