"""Rescale the ant so the soccer ball sits at LEG height, not torso height.

    python -m rower_soccer.tools.scale_ant --length-scale 2.7 --out creature_configs/ant_v2.xml

Why
---
The drills use dm_control's SOCCER ball (r=0.35 m, 0.045 kg), and that size is
not negotiable: it is set by the goal (23.8 m wide) and the pitch (96 x 72 m),
so shrinking it for a drill would make the drill stop matching the game. Matching
the ball is the creature's job -- the same rule `scene.py` states and that
`unity2mujoco.py --length-scale` exists for on the rower.

Measured on the ant as first built:

    ant torso under a trained policy   0.489 m
    ball diameter                      0.700 m      -> ratio 1.43
    dm_control quadruped fetch          0.570 m torso vs 0.300 m ball -> 0.53

At 1.43 the ball spans z in [0, 0.70] while the torso sphere spans [0.24, 0.74]:
they occupy the same band, so the ant can only shove the ball with its body. At
dm_control's 0.53 the ball sits below the belly and is shepherded with the legs.

What scales, and what deliberately does not
-------------------------------------------
LENGTH scales: geom sizes, fromto endpoints, body positions, joint positions.

MASS DOES NOT follow L^3. At constant density a 2.7x ant weighs 494 kg against a
45 g ball -- a 11000:1 ratio that makes the ball inertially invisible, and any
contact launches it. dm_control's own soccer env pairs a ~50 kg humanoid with
this exact ball (~1100:1), so density is reduced to hold mass near the original
25 kg and keep the soccer-like ratio we already have (557:1). (fetch's 8:1 is
the outlier: its ball is a 14 kg medicine ball, not a football.)

GEAR scales with length. Holding mass fixed while lengthening the limbs
multiplies the lever arm the legs work against, so the torque needed to support
and swing the body grows ~linearly in L; leaving gear alone would produce a
creature that cannot stand -- the exact failure mode the rower's gear_scale bug
caused, and which cost a 448M-step run.

ARMATURE and DAMPING scale with gear, per the invariance rule recorded in
three_seg_worm.xml's header: scaling them together leaves the joint dynamics
consistent rather than making the joints feel stiff or floppy at the new size.
"""

import argparse
import os
import re

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DEFAULT_IN = os.path.join(REPO, "creature_configs", "ant.xml")


def _scale_triplet(text, attr, k, n=None):
    """Multiply every number in attr="..." by k. n limits how many values."""
    def repl(m):
        vals = m.group(2).split()
        out = [f"{float(v) * k:.6g}" for v in vals[:n or len(vals)]]
        out += vals[len(out):]
        return f'{m.group(1)}="{" ".join(out)}"'
    return re.sub(rf'({attr})="([^"]+)"', repl, text)


def scale(src, length_scale, hold_mass=True):
    s = src
    # geometry
    s = _scale_triplet(s, "size", length_scale)
    s = _scale_triplet(s, "fromto", length_scale)
    s = _scale_triplet(s, "pos", length_scale)
    # actuation: torque must grow with the lever arm (see module docstring)
    s = _scale_triplet(s, "gear", length_scale)
    s = _scale_triplet(s, "armature", length_scale)
    s = _scale_triplet(s, "damping", length_scale)
    if hold_mass:
        # density / L^3 so total mass is unchanged; see docstring for why mass
        # must NOT follow L^3 against a 45 g ball.
        s = _scale_triplet(s, "density", 1.0 / length_scale ** 3)
    s = s.replace("<mujoco model=\"ant\">",
                  f"<mujoco model=\"ant_x{length_scale:g}\">")
    return s


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--in", dest="src", default=DEFAULT_IN)
    p.add_argument("--out", required=True)
    p.add_argument("--length-scale", type=float, default=2.7)
    p.add_argument("--grow-mass", action="store_true",
                   help="let mass follow L^3 (do not: see the module docstring)")
    a = p.parse_args()

    src = open(a.src).read()
    out = scale(src, a.length_scale, hold_mass=not a.grow_mass)
    note = (f"\n    <!-- GENERATED by rower_soccer.tools.scale_ant from "
            f"{os.path.basename(a.src)} at length_scale={a.length_scale:g}, "
            f"mass {'grown as L^3' if a.grow_mass else 'HELD constant'}. "
            f"Rationale in that module's docstring: the soccer ball is 0.70 m "
            f"across and cannot shrink, so the creature grows to meet it. -->")
    out = out.replace(">", ">" + note, 1)
    with open(a.out, "w") as f:
        f.write(out)
    print(f"wrote {a.out}")


if __name__ == "__main__":
    main()
