#!/usr/bin/env bash
# Rebuild Transform2Act's GPU virtualenv from nothing.
#
# Transform2Act is an upstream checkout, so everything we add to it -- the
# venv, env-gpu.sh, the *_gpu configs -- dies with the pod and comes back as
# archaeology. This is that archaeology, written down once. The pin rationale
# lives in docs/repro/TRANSFORM2ACT_M1_REPRO_NOTES.md ("Install landmines") and
# docs/T2A_GPU_PROFILE.md; this file is the executable form.
#
#   bash scripts/setup/rebuild_t2a_venv.sh            # full build
#   T2A_SKIP_APT=1 bash scripts/setup/rebuild_t2a_venv.sh
#
# Roughly 15 minutes and ~6 GB, most of it the cu111 wheels.
#
# The last step is not decoration: it asserts a real CUDA matmul and a real
# torch-scatter kernel both run. torch 1.8.0+cu111 ships SASS up to sm_86 with
# PTX, and this pod's card is sm_89 -- that works only through PTX JIT, so it
# has to be checked rather than assumed.
set -euo pipefail

T2A=${T2A_DIR:-/workspace/Transform2Act}
VENV=$T2A/.venv-gpu
MUJOCO=${MUJOCO_HOME:-$HOME/.mujoco/mujoco210}

echo "=== 0. preconditions"
[ -d "$T2A/design_opt" ] || { echo "no Transform2Act checkout at $T2A"; exit 1; }

if [ "${T2A_SKIP_APT:-0}" != "1" ]; then
  echo "=== 1. system packages (mujoco-py builds a cython ext against these)"
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
    libosmesa6-dev libglew-dev patchelf libgl1-mesa-dev libglfw3
fi

if [ ! -f "$MUJOCO/bin/libmujoco210.so" ]; then
  echo "=== 2. MuJoCo 2.1.0 binaries"
  mkdir -p "$(dirname "$MUJOCO")"
  curl -sSL -o /tmp/mujoco210.tar.gz \
    https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz
  # --no-same-owner: the tarball carries the packager's uid, which a container
  # cannot chown to, and tar exits nonzero over it while extracting fine.
  tar xzf /tmp/mujoco210.tar.gz -C "$(dirname "$MUJOCO")" --no-same-owner
  rm -f /tmp/mujoco210.tar.gz
fi
[ -f "$MUJOCO/bin/libmujoco210.so" ] || { echo "mujoco210 missing"; exit 1; }

UV=$(command -v uv || echo "$HOME/.local/bin/uv")
[ -x "$UV" ] || { echo "uv not found -- curl -LsSf https://astral.sh/uv/install.sh | sh"; exit 1; }

echo "=== 3. venv (python 3.9: the newest with torch 1.8.0 wheels)"
rm -rf "$VENV"
# --seed: uv omits pip by default, and the PyG wheel index needs pip's -f.
"$UV" venv --seed --python 3.9 "$VENV"
P=$VENV/bin/python

# A CONSTRAINTS FILE, applied to every install below rather than a pin on one
# line. torch 1.8's C extension is compiled against numpy 1.x and dies with
# "_ARRAY_API not found" under numpy 2 -- and the bump does not come from
# anything we ask for by name, it arrives transitively (scipy went 1.7.3 ->
# 1.13.1 and dragged numpy 1.21.6 -> 2.0.2 on a later, unrelated line). A
# per-line pin loses that race; -c wins it everywhere at once.
CONSTRAINTS=$VENV/constraints.txt
cat > "$CONSTRAINTS" <<'EOF'
numpy==1.22.4
scipy==1.7.3
EOF
pipi () { $P -m pip install -q -c "$CONSTRAINTS" "$@"; }

echo "=== 4. build deps first -- Cython<3 or mujoco-py's ext will not compile"
# scipy is here rather than with the rest of their requirements because
# torch-sparse declares it and step 6 runs under --no-index, which leaves
# pip unable to resolve it from PyPI at all.
pipi "setuptools==59.5.0" wheel numpy "Cython<3" scipy

echo "=== 5. torch 1.8.0+cu111"
pipi torch==1.8.0+cu111 \
  -f https://download.pytorch.org/whl/torch_stable.html

echo "=== 6. PyG extensions -- PINNED, from the cu111 index, --no-index"
# Unpinned, pip takes the latest PyPI sdist, compiles ~40 min single-core, and
# fails against torch 1.8 headers. These four are the cp39 wheels that exist.
pipi torch-scatter==2.0.8 torch-sparse==0.6.12 \
  torch-cluster==1.5.9 torch-spline-conv==1.2.1 \
  --no-index -f https://data.pyg.org/whl/torch-1.8.0+cu111.html
pipi nvidia-cuda-runtime-cu11 nvidia-cublas-cu11 nvidia-cusparse-cu11
pipi torch-geometric==1.6.1
# PyG 1.6.1 imports all four of these at import time; 0.5 renamed the module.
pipi googledrivedownloader==0.4 rdflib pandas==1.3.5 h5py

echo "=== 7. their requirements, pinned where a modern resolve breaks them"
pipi "gym==0.15.4" "opencv-python==4.5.5.64" glfw pyyaml \
  "tensorboard==2.11.2" "protobuf==3.20.3" lxml pillow
pipi "mujoco-py==2.1.2.14"

echo "=== 8. env-gpu.sh"
cat > "$T2A/env-gpu.sh" <<EOF
# source before every GPU run. Regenerated by rebuild_t2a_venv.sh.
export MUJOCO_PY_MUJOCO_PATH=$MUJOCO
export LD_LIBRARY_PATH=$MUJOCO/bin:\${LD_LIBRARY_PATH:-}
export MUJOCO_GL=osmesa       # headless; training never renders
export OMP_NUM_THREADS=1      # per their README; agent.py sets it too
export MKL_NUM_THREADS=1
# torch 1.8 links cuBLAS/cuSPARSE statically, so these are belt-and-braces.
_T2A_SP=$VENV/lib/python3.9/site-packages
export LD_LIBRARY_PATH=\$_T2A_SP/nvidia/cuda_runtime/lib:\$_T2A_SP/nvidia/cublas/lib:\$_T2A_SP/nvidia/cusparse/lib:\$LD_LIBRARY_PATH
EOF

echo "=== 9. verify -- imports, a real CUDA matmul, a real scatter kernel"
set +u; . "$T2A/env-gpu.sh"; set -u
cd "$T2A"
$P - <<'PY'
import torch, torch_scatter, torch_geometric, mujoco_py, gym
print("torch", torch.__version__, "cuda", torch.version.cuda,
      "available", torch.cuda.is_available())
assert torch.cuda.is_available(), "no CUDA device"
print("device:", torch.cuda.get_device_name(0),
      "sm_%d%d" % torch.cuda.get_device_capability(0))
# The JIT check. If sm_89 has no path here, this raises rather than returning
# a wrong answer -- which is the point of asserting on the value too.
torch.set_default_dtype(torch.float64)
a = torch.randn(512, 512, device="cuda")
assert torch.allclose(a @ torch.eye(512, device="cuda"), a, atol=1e-9)
src = torch.randn(1000, 8, device="cuda")
idx = torch.randint(0, 50, (1000,), device="cuda")
out = torch_scatter.scatter_add(src, idx, dim=0, dim_size=50)
ref = torch.zeros(50, 8, device="cuda").index_add_(0, idx, src)
assert torch.allclose(out, ref, atol=1e-12), "torch-scatter kernel is wrong"
print("cuda matmul OK, torch-scatter OK, mujoco_py", mujoco_py.__version__,
      "gym", gym.__version__)
print("torch_geometric", torch_geometric.__version__)
PY

echo
echo "=== done. $VENV"
echo "    cd $T2A && . env-gpu.sh && .venv-gpu/bin/python design_opt/train.py --cfg hopper_gpu --num_threads 32 --gpu_index 0"
